# SYSTEM LIMITS
fs.file-max = 2097152

# TCP / SYN FLOOD RESISTANCE
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 8192
net.core.somaxconn = 8192

# SOCKET LIFETIME RECOVERY
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
